#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

app_virement_show:
    path: '/virement/{id}'
    controller: 'App\Controller\VirementController::show'
    methods: ['GET']


