<?php

namespace ContainerK2t0qFj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A6CpSMcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A6CpSMc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A6CpSMc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ReclamtionRepository' => ['privates', 'App\\Repository\\ReclamtionRepository', 'getReclamtionRepositoryService', true],
            'chequeRepository' => ['privates', 'App\\Repository\\ChequeRepository', 'getChequeRepositoryService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'ReclamtionRepository' => 'App\\Repository\\ReclamtionRepository',
            'chequeRepository' => 'App\\Repository\\ChequeRepository',
            'managerRegistry' => '?',
        ]);
    }
}
