<?php

namespace ContainerK2t0qFj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Skuq6mWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Skuq6mW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Skuq6mW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'repository' => ['privates', 'App\\Repository\\ChequeRepository', 'getChequeRepositoryService', true],
        ], [
            'managerRegistry' => '?',
            'repository' => 'App\\Repository\\ChequeRepository',
        ]);
    }
}
