<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYMOx73L\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYMOx73L/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYMOx73L.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYMOx73L\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYMOx73L\App_KernelDevDebugContainer([
    'container.build_hash' => 'YMOx73L',
    'container.build_id' => 'd53b4fdf',
    'container.build_time' => 1709376376,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYMOx73L');
